### ISSUE TITLE
llvm-ar from stage2 is dynamically linked and against libstdc++ and libgcc_s

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/containers#16]
```sh
$ docker run -it ghcr.io/clangbuiltlinux/llvm-project:stage2 ash                        
/ # apk add file
/ # file /usr/local/bin/llvm-ar
/usr/local/bin/llvm-ar:   ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, with debug_info, not stripped
/ # ldd $(which llvm-ar) 2>&1 | head -n 4
	/lib/ld-musl-x86_64.so.1 (0x7fba2cd8c000)
	libz.so.1 => /lib/libz.so.1 (0x7fba2c66a000)
Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/bin/llvm-ar)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/bin/llvm-ar)
```
This is making it unusable for stage3.

**Comment by nickdesaulniers** [comment]
@compnerd @MaskRay seems like perhaps `CMAKE_EXE_LINKER_FLAGS` isn't being used to build `llvm-project/llvm/tools/`?

**Comment by compnerd** [comment]
https://github.com/llvm/llvm-project/blob/main/llvm/cmake/modules/AddLLVM.cmake#L895-L899
This would require going out of our way to drop the `CMAKE_EXE_LINKER_FLAGS`.  

https://github.com/llvm/llvm-project/blob/main/llvm/cmake/modules/AddLLVM.cmake#L273-L275 is where we tweak the linker flags.

I would suggest that you build this and look at the command invocation using `ninja -t commands`.

**Comment by nickdesaulniers** [comment]
nevermind, I didn't `install-llvm-ar` in stage2, so `/usr/local/bin/` contains `llvm-ar` from stage1.
