### ISSUE TITLE
Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/containers#34]
```
$ make epoch3
...
[+] Testing clang in 'docker.io/fedora:latest' container
[+] Testing 'clang --version'
clang version 14.0.1
Target: x86_64-alpine-linux-musl
Thread model: posix
InstalledDir: /repo/toolchain/bin
[+] Updating OS
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64 [getaddrinfo() thread failed to start]
make: *** [Makefile:32: epoch3] Error 1
```
cc @nathanchance

**Comment by nickdesaulniers** [comment]
is there something I need to do so that docker has network access, perhaps?

**Comment by nathanchance** [comment]
Hmmm, weird, flakiness with Fedora's mirrors? Does:

```
docker run --rm -ti docker.io/fedora:latest bash -c "dnf update -y"
```

work?

**Comment by nickdesaulniers** [comment]
```
$ docker run --rm -ti docker.io/fedora:latest bash -c "dnf update -y"
Fedora 36 - x86_64                                                                                                                                                                                         0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64 [getaddrinfo() thread failed to start]
```

**Comment by nathanchance** [comment]
Does Arch Linux work?

```
$ docker run --rm -ti docker.io/archlinux:latest bash -c "pacman -Syyu --noconfirm"
```

**Comment by nickdesaulniers** [comment]
> Does Arch Linux work?

Yep

---

No luck with:
```diff
diff --git a/ci/test-clang.sh b/ci/test-clang.sh
index a9a0c9b3fe4b..26fe385ac675 100755
--- a/ci/test-clang.sh
+++ b/ci/test-clang.sh
@@ -31,6 +31,7 @@ for docker_image in "${docker_images[@]}"; do
     echo "[+] Testing clang in '$docker_image' container"
     "$DOCKER" run \
         --rm \
+        --network host \
         --volume "$rootdir":/repo:ro,z \
         "$docker_image" \
         bash /repo/ci/test-clang-docker.sh
```

**Comment by nickdesaulniers** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2009047 looks related.

**Comment by nathanchance** [comment]
Seems like you might have an older `runc`?

I can move the tests to a separate target (`epoch<#>-test`?) to mitigate this when testing locally.

**Comment by nickdesaulniers** [comment]
> Seems like you might have an older runc?

That's what's in the docker container for fedora. It seems that you can't invoke `dnf` to update `runc` because of that?

https://github.com/ClangBuiltLinux/containers/pull/35. IDK if that's a good longer term solution though.

**Comment by nickdesaulniers** [comment]
https://pascalroeleven.nl/2021/09/09/ubuntu-21-10-and-fedora-35-in-docker/

**Comment by nickdesaulniers** [comment]
LOL

from https://pascalroeleven.nl/2021/09/09/ubuntu-21-10-and-fedora-35-in-docker/

> Hello fellow Googlers

**Comment by nathanchance** [comment]
> That's what's in the docker container for fedora. It seems that you can't invoke `dnf` to update `runc` because of that?

`runc` should be on your host, not in the container. For example, in the VMs for self-hosted actions:

```
$ podman run --rm -ti docker.io/fedora:latest bash -c "command -v runc"

$ runc --version
runc version 1.1.2
commit: v1.1.2-0-ga916309
spec: 1.0.2-dev
go: go1.17.11
libseccomp: 2.5.3
```

> #35. IDK if that's a good longer term solution though.

Probably not but we can merge it to unblock you.

**Comment by nathanchance** [comment]
Did you install Docker using [their official instructions](https://docs.docker.com/engine/install/debian/)? If so, that seems expected, as `containerd.io` contains `runc`.

**Comment by nickdesaulniers** [comment]
I'm pretty sure IIRC that I can't run
https://docs.docker.com/engine/install/debian/#set-up-the-repository
to add external sources that would avoid Google's allowlist proxies.

Maybe I ran https://docs.docker.com/engine/install/debian/#install-from-a-package and I need to update containerd.io.

**Comment by nickdesaulniers** [comment]
```sh
$ wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/containerd.io_1.6.6-1_amd64.deb
$ sudo dpkg -i containerd.io_1.6.6-1_amd64.deb
$ containerd --version
containerd containerd.io 1.6.6 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
$ runc --version
runc version 1.1.2
commit: v1.1.2-0-ga916309
spec: 1.0.2-dev
go: go1.17.11
libseccomp: 2.5.3
```
That should work, but I have to rebuild my containers now since I wiped all of my local ones...

**Comment by nickdesaulniers** [comment]
:( same issue even with runc v1.1.2

**Comment by nickdesaulniers** [comment]
Looking at
https://github.com/moby/moby/pull/42681 and https://github.com/Netflix/titus-executor/pull/894/files and https://docs.docker.com/engine/security/seccomp/, it looks like

> The default Docker profile can be found [here](https://github.com/moby/moby/blob/master/profiles/seccomp/default.json).

That seems maybe safer to use (and mentions clone3) than nothing.

**Comment by nickdesaulniers** [comment]
https://github.com/moby/moby/issues/42680
https://github.com/moby/moby/commit/9f6b562dd12ef7b1f9e2f8e6f2ab6477790a6594

**Comment by nickdesaulniers** [comment]
> That seems maybe safer to use (and mentions clone3) than nothing.

Adding that to the repo then:
```diff
diff --git a/ci/test-clang.sh b/ci/test-clang.sh
index 8013068ec103..6e8cc0edd37c 100755
--- a/ci/test-clang.sh
+++ b/ci/test-clang.sh
@@ -31,7 +31,7 @@ for docker_image in "${docker_images[@]}"; do
     echo "[+] Testing clang in '$docker_image' container"
     "$DOCKER" run \
         --rm \
-        --security-opt seccomp=unconfined \
+        --security-opt seccomp="$rootdir"/ci/default.json \
         --volume "$rootdir":/repo:ro,z \
         "$docker_image" \
         bash /repo/ci/test-clang-docker.sh
```
still doesn't resolve the issue for me...
